### ISSUE TITLE
Request for amd64 Architecture Support for Linux

### ISSUE THREAD

**Issue by eliawehbe** [dresktop/dresktop#10]
Hi there,

I’m interested in using Dresktop on my Ubuntu system, but I noticed that the current version only supports the ARM64 architecture. Are there any plans to release an amd64 version for Linux? It would be fantastic to have compatibility with standard 64-bit x86 systems.

Thanks for your hard work on this project—I’m excited to try Dresktop!

**Comment by jdeg** [comment]
Hi @eliawehbe,

Thanks for your interest in Dresktop! Yes, I am planning to release a version for 64-bit x86 systems as well as for Windows OS. Currently, I can only test the app on macOS and Ubuntu for ARM64 architectures, but I'm hoping to acquire a device soon to begin testing and releasing for additional architectures.

In the meantime, you can clone the repository and build it locally on your system—it should compile without issues on your architecture.
