### ISSUE TITLE
install on Ubuntu 22.04 fails because of wrong architecture

### ISSUE THREAD

**Issue by heliogabal** [dresktop/dresktop#2]
Hey, this looks like a very promising piece of software, I'm eager to test it out. But I stumbled upon a problem before the beginning...

I downloaded https://github.com/dresktop/dresktop/releases/download/v1.0.1-beta.0/Dresktop-Linux-1.0.1-beta.0.deb to install it on my Ubuntu 22.04.4 LTS 64bit laptop, but I get this error message: 

```
sudo apt install ./Dresktop-Linux-1.0.1-beta.0.deb 
Paketlisten werden gelesen… Fertig
Abhängigkeitsbaum wird aufgebaut… Fertig
Statusinformationen werden eingelesen… Fertig
Hinweis: »dresktop:arm64« wird an Stelle von »./Dresktop-Linux-1.0.1-beta.0.deb« gewählt.
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 dresktop:arm64 : Hängt ab von: libgtk-3-0:arm64 ist aber nicht installierbar
                  Hängt ab von: libnotify4:arm64 ist aber nicht installierbar
                  Hängt ab von: libnss3:arm64 ist aber nicht installierbar
                  Hängt ab von: libxss1:arm64 ist aber nicht installierbar
                  Hängt ab von: libxtst6:arm64 ist aber nicht installierbar
                  Hängt ab von: libatspi2.0-0:arm64 ist aber nicht installierbar
                  Hängt ab von: libuuid1:arm64 ist aber nicht installierbar
                  Hängt ab von: libsecret-1-0:arm64 ist aber nicht installierbar
                  Empfiehlt: libappindicator3-1:arm64 ist aber nicht installierbar
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.
```
So there seems to be some mixup with the architecture in the package. It clearly should be amd64 and not arm64. Could you recreate the package so it's working with Ubuntu? I couldn't find any documentation on how to install the sources directly, so I kind of need the .deb to move on. Thanks!

**Comment by jdeg** [comment]
Hi Rainer, thanks for your feedback!

It seems like the problem is the architecture. I was only able to compile and test the application on arm64 architecture for Mac and Ubuntu. I can build the x86_64 version for you using Github Actions, but I don't have a x86_64 computer to test it on. 

Another option is to download the repository and compile it for your architecture using `npm run build`

The only dependencies per architecture are @rollup/rollup-linux-arm64-gnu and @rollup/rollup-darwin-arm64.
