### ISSUE TITLE
Missing Documentation for Database Configuration

### ISSUE THREAD

**Issue by mvessuri** [dresktop/dresktop#9]
## Issue
The project lacks documentation for database connection configuration in local environments.

## Details
The following database configuration details should be added to README.md or the Get Started guide:

- Database: drupal
- Username: drupal
- Password: drupal
- Host: database

## Proposed Solution
Update README.md or the Get Started guide with this information to help developers set up their local environments more easily.

**Comment by jdeg** [comment]
I have updated the README.md file to include the necessary database configuration details for setting up local environments, as well as the documentation at dresktop.com.

Thank you very much for the feedback!
